---
# tasks file for atividade03
- name: Instalar Git e Apache2
  apt:
    pkg:
    - git
    - apache2
  notify:
  - Iniciar Apache2
  register: apacheinstall

- name: Status da instalacao de pacotes
  ansible.builtin.debug:
    var: apacheinstall
    verbosity: 1

- name: Clonar repositorio do git
  git:
    repo: '{{ gitrepo }}'
    dest: '{{ gitdest }}'
  when: apacheinstall is success
  register: gitclone
  
- name: Status da clonagem do repositorio
  ansible.builtin.debug:
    var: gitclone
    verbosity: 1

- name: Criar soft link para inde.html
  file:
    src: '{{ gitdest }}/inde.html'
    dest: '{{ gitdest }}/index.html'
    state: link
  notify:
  - Reiniciar Apache2
  when: gitclone is success
